# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200505_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
