# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.CharField(choices=[('1', 'Spectre in the Ballroom'), ('2', 'The Hunting Party'), ('3', 'The Corpse in the Drawing Room'), ('4', 'A Time to Kill'), ('5', 'The Casino Killing')], default='1', max_length=20),
        ),
    ]
