# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-03 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.CharField(choices=[('Spectre in the Ballroom', 'Spectre in the Ballroom'), ('The Hunting Party', 'The Hunting Party'), ('The Corpse in the Drawing Room', 'The Corpse in the Drawing Room'), ('A Time to Kill', 'A Time to Kill'), ('The Casino Killing', 'The Casino Killing')], default='Spectre in the Ballroom', max_length=20),
        ),
    ]
