# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(default=''),
        ),
    ]
