# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
