# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200415_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='postcode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='street',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='town',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
